"""
Layer 1 known-answer tests — spike encoding comparison study.

=============================================================================
AUTHORED BY THE DESIGN SESSION, FROM THE DEFINING EQUATIONS, WITHOUT SIGHT OF
ANY IMPLEMENTATION. DO NOT EDIT THIS FILE TO MAKE A FAILING TEST PASS.

Every expected value here is derived from the mathematics in
docs/proposal_v2.md, not from observed behaviour of the code. That is the whole
point: a test whose expected value came from the implementation cannot detect
an error in the implementation.

If you believe a test is wrong, stop, write the argument in QUESTIONS.md, and
work on something else. See §3 of docs/validation_protocol.md and the
precedence rules in CLAUDE.md.
=============================================================================

Equation numbers in comments refer to docs/proposal_v2.md.
All of these fail with ImportError until spikeenc exists. That is expected.
"""
import numpy as np
import pytest

from conftest import (
    DT, FS, constant_drive, ramp_drive, sine_drive, step_drive,
    tone, harmonic_complex, speechlike, drive_for, all_encoders,
)

from spikeenc import SpikeTrain
from spikeenc import encoders as E
from spikeenc import features, metrics, corrupt
from spikeenc.frontend import Filterbank


def _rank(x):
    """Ranks, ties averaged. Avoids a scipy dependency."""
    order = np.argsort(x, kind="mergesort")
    ranks = np.empty(len(x), dtype=float)
    ranks[order] = np.arange(len(x), dtype=float)
    return ranks


def _spearman(a, b):
    ra, rb = _rank(np.asarray(a)), _rank(np.asarray(b))
    ra = ra - ra.mean()
    rb = rb - rb.mean()
    denom = np.sqrt((ra**2).sum() * (rb**2).sum())
    return 0.0 if denom == 0 else float((ra * rb).sum() / denom)


# ===========================================================================
# G — generic properties every encoder must have
# ===========================================================================

def test_G1_determinism(encoder_case):
    """Identical input, identical output. Arrays compared elementwise."""
    label, cls, kwargs = encoder_case
    enc = cls(**kwargs)
    drive = drive_for(cls)
    a = enc.encode_from_drive(drive, DT, seed=1234)
    b = enc.encode_from_drive(drive, DT, seed=1234)
    np.testing.assert_array_equal(a.channel, b.channel)
    np.testing.assert_array_equal(a.time, b.time)
    np.testing.assert_array_equal(a.polarity, b.polarity)


def test_G2_silence_produces_no_events(encoder_case):
    """SPEC §4.1: all-zero drive produces zero events, for every encoder."""
    label, cls, kwargs = encoder_case
    enc = cls(**kwargs)
    drive = np.zeros((kwargs["n_channels"], int(1.0 / DT)))
    train = enc.encode_from_drive(drive, DT, seed=0)
    assert len(train) == 0, f"{label} emitted {len(train)} events on silence"


def test_G3_rate_parameter_is_monotonic(encoder_case):
    """Sweeping the declared rate parameter moves the event count monotonically
    in the declared direction. Without this, matched-budget comparison (§6.4)
    is not possible."""
    label, cls, kwargs = encoder_case
    drive = drive_for(cls, duration=2.0)
    base = kwargs[cls.RATE_PARAM]
    counts = []
    for factor in (0.25, 0.5, 1.0, 2.0, 4.0):
        kw = dict(kwargs)
        kw[cls.RATE_PARAM] = base * factor
        counts.append(len(cls(**kw).encode_from_drive(drive, DT, seed=0)))
    counts = np.array(counts)
    if cls.RATE_DIRECTION < 0:
        assert np.all(np.diff(counts) <= 0), f"{label} not monotonic: {counts}"
        assert counts[0] > counts[-1], f"{label} rate parameter has no effect: {counts}"
    else:
        assert np.all(np.diff(counts) >= 0), f"{label} not monotonic: {counts}"
        assert counts[-1] > counts[0], f"{label} rate parameter has no effect: {counts}"


def test_G4_time_shift_equivariance(encoder_case):
    """Delaying the drive delays every event by the same amount.

    The shift is 0.1 s = 1600 samples = an integer number of frames at the
    default 10 ms hop, so framed encoders are not disadvantaged.
    """
    label, cls, kwargs = encoder_case
    enc = cls(**kwargs)
    drive = drive_for(cls, duration=1.0)
    shift_s = 0.1
    pad = np.zeros((drive.shape[0], int(round(shift_s / DT))))
    a = enc.encode_from_drive(drive, DT, seed=7)
    b = enc.encode_from_drive(np.hstack([pad, drive]), DT, seed=7)
    assert len(a) == len(b), f"{label}: {len(a)} vs {len(b)} events after shift"
    if len(a):
        delta = np.sort(b.time) - np.sort(a.time)
        assert np.max(np.abs(delta - shift_s)) < 2 * DT


def test_G7_event_validity(encoder_case):
    """Canonical ordering, times in range, polarities legal (SPEC §2)."""
    label, cls, kwargs = encoder_case
    enc = cls(**kwargs)
    drive = drive_for(cls, duration=1.0)
    train = enc.encode_from_drive(drive, DT, seed=0)
    assert np.all(np.diff(train.time) >= 0), f"{label} events not time-sorted"
    assert np.all(train.time >= 0.0)
    assert np.all(train.time <= train.duration + DT)
    assert np.all(np.isin(train.polarity, (-1, 1)))
    assert np.all(train.channel >= 0)
    assert np.all(train.channel < train.n_channels)


def test_G7b_refractory_is_respected(encoder_case):
    """No two events in a channel closer than the refractory period."""
    label, cls, kwargs = encoder_case
    kw = dict(kwargs)
    if "refractory" not in cls.__init__.__code__.co_varnames:
        pytest.skip(f"{label} has no refractory parameter")
    kw["refractory"] = 0.004
    enc = cls(**kw)
    train = enc.encode_from_drive(drive_for(cls, duration=1.0), DT, seed=0)
    for c in range(kw["n_channels"]):
        t = train.times_in_channel(c)
        if len(t) > 1:
            assert np.min(np.diff(t)) >= 0.004 - DT, f"{label} channel {c}"


def test_G8_featurisation_is_order_invariant(encoder_case):
    """SPEC §5. Shuffling the event arrays must not change the features."""
    label, cls, kwargs = encoder_case
    enc = cls(**kwargs)
    train = enc.encode_from_drive(drive_for(cls), DT, seed=0)
    if len(train) < 2:
        pytest.skip("too few events")
    rng = np.random.default_rng(0)
    perm = rng.permutation(len(train))
    shuffled = SpikeTrain(
        channel=train.channel[perm], time=train.time[perm],
        polarity=train.polarity[perm], n_channels=train.n_channels,
        duration=train.duration, params=train.params,
    )
    np.testing.assert_allclose(features.featurise(train),
                               features.featurise(shuffled), rtol=1e-10)


# ===========================================================================
# F — front end (proposal §5.0, equations 4-10)
# ===========================================================================

def test_F1_centre_frequencies_match_impulse_responses():
    """The spectral peak of each gammatone impulse response sits at its nominal
    centre frequency, within 1 per cent. Equation (4)."""
    fb = Filterbank(n_channels=16, f_min=100.0, f_max=6000.0, sample_rate=FS)
    n = 4096
    for c in range(fb.n_channels):
        h = fb.impulse_response(c, n)
        spectrum = np.abs(np.fft.rfft(h, n=8 * n))
        freqs = np.fft.rfftfreq(8 * n, d=1.0 / FS)
        peak = freqs[np.argmax(spectrum)]
        nominal = fb.centre_frequencies[c]
        assert abs(peak - nominal) / nominal < 0.01, (
            f"channel {c}: peak {peak:.1f} Hz vs nominal {nominal:.1f} Hz")


def test_F2_bandwidths_follow_glasberg_moore():
    """b_c = 1.019 * ERB(f_c), with ERB from equation (5)."""
    fb = Filterbank(n_channels=16, f_min=100.0, f_max=6000.0, sample_rate=FS)
    erb = 24.7 * (0.00437 * fb.centre_frequencies + 1.0)
    np.testing.assert_allclose(fb.bandwidths, 1.019 * erb, rtol=1e-6)


def test_F3_erb_spacing_is_uniform():
    """Centre frequencies uniform on the ERB-rate scale, equation (6),
    ascending, and hitting the endpoints exactly."""
    fb = Filterbank(n_channels=32, f_min=80.0, f_max=7000.0, spacing="erb")
    fc = fb.centre_frequencies
    assert np.all(np.diff(fc) > 0), "centre frequencies must ascend"
    assert abs(fc[0] - 80.0) < 1e-6 and abs(fc[-1] - 7000.0) < 1e-6
    e = 21.4 * np.log10(0.00437 * fc + 1.0)
    steps = np.diff(e)
    assert np.std(steps) / np.mean(steps) < 1e-6


def test_F4_envelope_tracks_amplitude_modulation():
    """The envelope of an AM tone recovers the modulator. Equations (8)-(9)."""
    fb = Filterbank(n_channels=24, f_min=100.0, f_max=6000.0, sample_rate=FS)
    fc_target = 1000.0
    c = int(np.argmin(np.abs(fb.centre_frequencies - fc_target)))
    n = FS
    t = np.arange(n) / FS
    modulator = 1.0 + 0.5 * np.sin(2 * np.pi * 5 * t)
    audio = modulator * np.sin(2 * np.pi * fb.centre_frequencies[c] * t)
    env = fb.envelope(audio, method="hilbert")[c]
    trim = FS // 10                      # discard filter startup transient
    r = np.corrcoef(env[trim:-trim], modulator[trim:-trim])[0, 1]
    assert r > 0.95, f"envelope/modulator correlation {r:.3f}"


def test_F5_subbands_conserve_energy_approximately():
    """Summed subband energy is of the same order as input energy: catches
    normalisation applied twice, or not at all."""
    fb = Filterbank(n_channels=32, f_min=100.0, f_max=6000.0, sample_rate=FS)
    audio = speechlike(duration=1.0)
    sub = fb.subbands(audio)
    ratio = np.sum(sub**2) / np.sum(audio**2)
    assert 0.2 < ratio < 20.0, f"subband/input energy ratio {ratio:.3f}"


# ===========================================================================
# E1 — LIF. Closed-form firing period, equation (V1) of the protocol.
# ===========================================================================

def test_T1_1_constant_drive_gives_closed_form_interval():
    """T = tau_m * ln(V_inf / (V_inf - theta)).

    With gain 1, drive 2.0, theta 1.0, tau_m 0.02:
        T = 0.02 * ln(2/1) = 0.0138629 s
    """
    theta, tau_m, u = 1.0, 0.02, 2.0
    expected = tau_m * np.log(u / (u - theta))
    enc = E.LIF(n_channels=1, theta=theta, tau_m=tau_m, gain=1.0, refractory=0.0)
    train = enc.encode_from_drive(constant_drive(u, n_channels=1, duration=1.0), DT)
    t = train.times_in_channel(0)
    assert len(t) > 10, "expected repeated firing under constant drive"
    isi = np.median(np.diff(t))
    assert abs(isi - expected) < 1.5 * DT, (
        f"ISI {isi:.6f} s, closed form predicts {expected:.6f} s")


def test_T1_2_subthreshold_drive_is_silent():
    """V_inf <= theta must produce no events at all."""
    enc = E.LIF(n_channels=1, theta=1.0, tau_m=0.02, gain=1.0, refractory=0.0)
    train = enc.encode_from_drive(constant_drive(0.95, n_channels=1, duration=2.0), DT)
    assert len(train) == 0


def test_T1_3_refractory_caps_the_rate():
    """Firing rate saturates at 1/refractory however large the drive."""
    ref = 0.005
    enc = E.LIF(n_channels=1, theta=1.0, tau_m=0.02, gain=1.0, refractory=ref)
    train = enc.encode_from_drive(constant_drive(500.0, n_channels=1, duration=1.0), DT)
    t = train.times_in_channel(0)
    assert len(t) > 1
    assert np.min(np.diff(t)) >= ref - DT
    assert len(t) <= 1.0 / ref + 1


# ===========================================================================
# E2 — Send-on-delta. Equations (14)-(17); the sharpest tests in the suite.
# ===========================================================================

@pytest.mark.parametrize("signal_name", ["noise", "chirp", "sine", "ramp"])
def test_T2_1_reconstruction_error_is_bounded_by_C(signal_name):
    """Equation (16): |u(t) - r(t)| < C, always. This is a theorem, not a
    tolerance. The reference is reconstructed from the event stream alone,
    which is what a downstream user of the release would do."""
    C = 0.1
    n = int(1.0 / DT)
    t = np.arange(n) * DT
    if signal_name == "noise":
        u = np.cumsum(np.random.default_rng(0).standard_normal(n)) * 0.01
    elif signal_name == "chirp":
        u = np.sin(2 * np.pi * (5 + 40 * t) * t)
    elif signal_name == "sine":
        u = 2.0 * np.sin(2 * np.pi * 7 * t)
    else:
        u = 3.0 * t
    drive = u[None, :]

    enc = E.SendOnDelta(n_channels=1, C=C, refractory=0.0,
                        reference_update="lattice")
    train = enc.encode_from_drive(drive, DT)

    # r(t) = u[0] + C * (cumulative signed event count)
    r = np.full(n, u[0])
    idx = np.clip(np.round(train.time / DT).astype(int), 0, n - 1)
    steps = np.zeros(n)
    np.add.at(steps, idx, C * train.polarity.astype(float))
    r = u[0] + np.cumsum(steps)

    err = np.max(np.abs(u - r))
    assert err < C + 1e-9, f"{signal_name}: max reconstruction error {err:.6f} >= C={C}"


def test_T2_2_event_count_follows_total_variation():
    """Equation (17): N = (1/C) * integral |du/dt| dt.

    For u = A sin(2*pi*f*t) the total variation over duration D is 4*A*f*D.
    With A=1, f=5, D=2: TV = 40, so N = 40/C = 400 at C=0.1.
    Tolerance allows one lost event per turning point (2*f*D = 20 of them).
    """
    A, f, D, C = 1.0, 5.0, 2.0, 0.1
    predicted = 4 * A * f * D / C
    slack = 2 * f * D + 2
    enc = E.SendOnDelta(n_channels=1, C=C, refractory=0.0)
    n = len(enc.encode_from_drive(sine_drive(A, f, n_channels=1, duration=D), DT))
    assert predicted - slack <= n <= predicted + slack, (
        f"{n} events, total variation predicts {predicted:.0f} (+/- {slack:.0f})")


def test_T2_3_linear_ramp_gives_regular_intervals():
    """A ramp of slope s produces events at exactly C/s, all of one polarity.
    Sharp test of the reference-update logic. s=10, C=0.5 -> 0.05 s intervals."""
    s, C = 10.0, 0.5
    enc = E.SendOnDelta(n_channels=1, C=C, refractory=0.0)
    train = enc.encode_from_drive(ramp_drive(s, n_channels=1, duration=1.0), DT)
    t = train.times_in_channel(0)
    assert len(t) in (19, 20), f"expected 19-20 events, got {len(t)}"
    assert np.all(train.polarity == 1), "a monotonic rise must give only ON events"
    np.testing.assert_allclose(np.diff(t), C / s, atol=1.5 * DT)


def test_T2_4_polarity_balances_over_a_closed_loop():
    """A signal returning to its starting value must emit equal ON and OFF
    counts. Follows exactly from equation (16)."""
    enc = E.SendOnDelta(n_channels=1, C=0.1, refractory=0.0)
    train = enc.encode_from_drive(sine_drive(1.0, 5.0, n_channels=1, duration=2.0), DT)
    n_on = int(np.sum(train.polarity == 1))
    n_off = int(np.sum(train.polarity == -1))
    assert n_on == n_off, f"ON {n_on} vs OFF {n_off}"


def test_T2_5_halving_C_doubles_the_event_count():
    """Direct check of the 1/C relation implied by equation (17)."""
    drive = sine_drive(1.0, 5.0, n_channels=1, duration=2.0)
    n_coarse = len(E.SendOnDelta(n_channels=1, C=0.2, refractory=0.0)
                   .encode_from_drive(drive, DT))
    n_fine = len(E.SendOnDelta(n_channels=1, C=0.1, refractory=0.0)
                 .encode_from_drive(drive, DT))
    assert 1.8 < n_fine / n_coarse < 2.2, f"ratio {n_fine / n_coarse:.3f}"


# ===========================================================================
# E3 — Temporal contrast. Equations (18)-(21).
# The risk is that E3 is accidentally implemented as E2; T3.1 and T3.2 exist
# specifically to detect that.
# ===========================================================================

def test_T3_1_steady_state_is_permanently_silent():
    """Constant drive: both filters track it, their difference is zero, and no
    event is ever emitted. E2 would settle; E3 must never fire at all."""
    enc = E.TemporalContrast(n_channels=1, theta=0.2,
                             tau_fast=0.001, tau_slow=0.05, refractory=0.0)
    train = enc.encode_from_drive(constant_drive(5.0, n_channels=1, duration=2.0), DT)
    assert len(train) == 0, f"{len(train)} events on constant drive"


def test_T3_2_slow_ramp_separates_E3_from_E2():
    """For a ramp of slope s the steady-state difference is s*(tau_slow -
    tau_fast). With s=2, tau_slow=0.05, tau_fast=0.001 that is 0.098, well
    below theta=0.5, so E3 must be silent. E2 on identical input fires
    repeatedly. If both fire, E3 is not bandpass."""
    s = 2.0
    drive = ramp_drive(s, n_channels=1, duration=2.0)
    e3 = E.TemporalContrast(n_channels=1, theta=0.5,
                            tau_fast=0.001, tau_slow=0.05, refractory=0.0)
    e2 = E.SendOnDelta(n_channels=1, C=0.1, refractory=0.0)
    n3 = len(e3.encode_from_drive(drive, DT))
    n2 = len(e2.encode_from_drive(drive, DT))
    assert n3 == 0, f"E3 emitted {n3} events on a slow ramp"
    assert n2 > 20, f"E2 emitted only {n2} events; check the test signal"


def test_T3_3_difference_of_exponentials_peaks_at_geometric_mean():
    """|H(w)| = |1/(1+jw*tau_f) - 1/(1+jw*tau_s)| peaks at w = 1/sqrt(tau_f*tau_s).

    With tau_f=1 ms, tau_s=50 ms that is 22.5 Hz. Tested on the amplitude of
    the internal difference signal rather than on event count, because event
    count also scales with modulation frequency and is not monotonic in |H|.
    """
    tau_f, tau_s = 0.001, 0.05
    f_peak = 1.0 / (2 * np.pi * np.sqrt(tau_f * tau_s))
    enc = E.TemporalContrast(n_channels=1, theta=1e9,   # never fires; we want the trace
                             tau_fast=tau_f, tau_slow=tau_s, refractory=0.0)
    amplitudes = {}
    for f_mod in (2.0, f_peak, 300.0):
        drive = sine_drive(1.0, f_mod, n_channels=1, duration=2.0)
        _, state = enc.encode_from_drive(drive, DT, return_state=True)
        trim = int(0.5 / DT)            # discard startup
        amplitudes[f_mod] = np.max(np.abs(state["d"][0, trim:]))
    assert amplitudes[f_peak] > amplitudes[2.0]
    assert amplitudes[f_peak] > amplitudes[300.0]


def test_T3_4_negating_the_drive_swaps_on_and_off():
    """Symmetric thresholds imply exact exchange of polarities."""
    enc = E.TemporalContrast(n_channels=1, theta=0.2,
                             tau_fast=0.001, tau_slow=0.05, refractory=0.0)
    drive = sine_drive(1.0, 8.0, n_channels=1, duration=1.0)
    a = enc.encode_from_drive(drive, DT)
    b = enc.encode_from_drive(-drive, DT)
    assert int(np.sum(a.polarity == 1)) == int(np.sum(b.polarity == -1))
    assert int(np.sum(a.polarity == -1)) == int(np.sum(b.polarity == 1))


# ===========================================================================
# E4 — Adaptive-threshold LIF. Equations (22)-(23).
# ===========================================================================

def test_T4_1_zero_adaptation_reduces_exactly_to_E1():
    """The single most valuable test for E4: with delta_a = 0 it must be
    indistinguishable from E1 at matched parameters."""
    drive = drive_for(E.LIF, n_channels=4, duration=1.0)
    lif = E.LIF(n_channels=4, theta=1.0, tau_m=0.02, gain=1.0, refractory=0.0)
    alif = E.ALIF(n_channels=4, theta_0=1.0, delta_a=0.0, tau_a=0.1,
                  tau_m=0.02, gain=1.0, refractory=0.0)
    a = lif.encode_from_drive(drive, DT)
    b = alif.encode_from_drive(drive, DT)
    np.testing.assert_array_equal(a.channel, b.channel)
    np.testing.assert_array_equal(a.time, b.time)


def test_T4_2_threshold_decays_geometrically_after_a_spike():
    """After an isolated event the threshold follows theta_0 + delta_a * rho^n
    with rho = exp(-dt/tau_a). Asserted on the state trace, not on firing."""
    theta_0, delta_a, tau_a = 1.0, 0.5, 0.05
    rho = np.exp(-DT / tau_a)
    enc = E.ALIF(n_channels=1, theta_0=theta_0, delta_a=delta_a, tau_a=tau_a,
                 tau_m=0.02, gain=1.0, refractory=0.0)
    # brief pulse, then silence: one burst then a long decay to observe
    drive = step_drive(0.0, 3.0, 0.0, n_channels=1, duration=0.02)
    tail = np.zeros((1, int(0.3 / DT)))
    drive = np.hstack([drive, tail])
    train, state = enc.encode_from_drive(drive, DT, return_state=True)
    assert len(train) > 0
    last = int(round(train.time[-1] / DT))
    thr = state["threshold"][0]
    start = last + 2
    window = thr[start:start + int(0.05 / DT)] - theta_0
    assert window[0] > 1e-6, "threshold did not rise after an event"
    predicted = window[0] * rho ** np.arange(len(window))
    np.testing.assert_allclose(window, predicted, rtol=1e-6, atol=1e-9)


def test_T4_3_adaptation_emphasises_onsets():
    """A step drive gives a burst then decay. The ratio of early to late event
    counts exceeds one, and grows with adaptation strength."""
    drive = step_drive(0.0, 3.0, 0.1, n_channels=1, duration=1.0)
    ratios = []
    for delta_a in (0.0, 0.5, 2.0):
        enc = E.ALIF(n_channels=1, theta_0=1.0, delta_a=delta_a, tau_a=0.1,
                     tau_m=0.02, gain=1.0, refractory=0.0)
        t = enc.encode_from_drive(drive, DT).times_in_channel(0)
        early = int(np.sum((t >= 0.10) & (t < 0.15)))
        late = int(np.sum((t >= 0.50) & (t < 0.55)))
        ratios.append(early / max(late, 1))
    assert ratios[0] == pytest.approx(1.0, abs=0.25), "no adaptation, no emphasis"
    assert ratios[1] > 1.1
    assert ratios[2] > ratios[1]


def test_T4_4_adaptation_suppresses_the_steady_state():
    """Sustained firing rate falls monotonically as adaptation strengthens."""
    drive = constant_drive(3.0, n_channels=1, duration=2.0)
    rates = []
    for delta_a in (0.0, 0.25, 1.0, 4.0):
        enc = E.ALIF(n_channels=1, theta_0=1.0, delta_a=delta_a, tau_a=0.1,
                     tau_m=0.02, gain=1.0, refractory=0.0)
        t = enc.encode_from_drive(drive, DT).times_in_channel(0)
        rates.append(int(np.sum(t > 1.0)))       # second half only
    assert np.all(np.diff(rates) <= 0), f"steady-state rates not decreasing: {rates}"
    assert rates[0] > rates[-1]


# ===========================================================================
# E5 — Phase locking. Equation (26) and the Gaussian jitter law.
# ===========================================================================

def test_T5_1_pure_tone_below_cutoff_locks_tightly():
    """Vector strength above 0.9 for a tone the encoder is meant to lock to."""
    f = 200.0
    x = tone(f, duration=1.0)
    enc = E.PhaseLocked(n_channels=1, threshold=0.05, f_lock=1500.0,
                        refractory=0.001, mode="deterministic",
                        centre_frequencies=np.array([f]))
    train = enc.encode_from_drive(x[None, :], DT)
    vs = metrics.vector_strength(train.times_in_channel(0), f)
    assert vs > 0.9, f"vector strength {vs:.3f}"


def test_T5_2_above_cutoff_locking_is_lost():
    """Above f_lock the encoder reverts to envelope behaviour, so events bear
    no fixed phase relationship to the carrier."""
    f = 5000.0
    x = tone(f, duration=1.0)
    enc = E.PhaseLocked(n_channels=1, threshold=0.05, f_lock=1500.0,
                        refractory=0.001, mode="deterministic",
                        centre_frequencies=np.array([f]))
    train = enc.encode_from_drive(x[None, :], DT)
    vs = metrics.vector_strength(train.times_in_channel(0), f)
    assert vs < 0.35, f"vector strength {vs:.3f} — still locking above cutoff"


def test_T5_3_interspike_intervals_recover_F0():
    """For a harmonic complex the pooled ISI histogram peaks at 1/F0.
    This is the one job the encoder exists to do."""
    f0 = 125.0
    x = harmonic_complex(f0, n_harmonics=8, duration=1.0)
    enc = E.PhaseLocked(n_channels=1, threshold=0.05, f_lock=1500.0,
                        refractory=0.001, mode="deterministic",
                        centre_frequencies=np.array([f0]))
    t = enc.encode_from_drive(x[None, :], DT).times_in_channel(0)
    isi = np.diff(t)
    assert len(isi) > 20
    hist, edges = np.histogram(isi, bins=200, range=(0.0, 0.05))
    peak = 0.5 * (edges[np.argmax(hist)] + edges[np.argmax(hist) + 1])
    assert abs(peak - 1.0 / f0) < 0.1 / f0, (
        f"ISI mode {peak * 1000:.2f} ms, expected {1000 / f0:.2f} ms")


@pytest.mark.parametrize("sigma", [0.0005, 0.001])
def test_T5_4_jitter_degrades_vector_strength_by_the_gaussian_law(sigma):
    """VS(sigma)/VS(0) = exp(-2 * pi^2 * sigma^2 * f^2).

    Validates both the encoder and the jitter operator used in P2. At f=200 Hz:
      sigma=0.5 ms -> 0.821,  sigma=1.0 ms -> 0.454
    """
    f = 200.0
    x = tone(f, duration=2.0)
    enc = E.PhaseLocked(n_channels=1, threshold=0.05, f_lock=1500.0,
                        refractory=0.001, mode="deterministic",
                        centre_frequencies=np.array([f]))
    clean = enc.encode_from_drive(x[None, :], DT)
    vs0 = metrics.vector_strength(clean.times_in_channel(0), f)
    rng = np.random.default_rng(0)
    ratios = []
    for _ in range(5):
        j = corrupt.jitter(clean, sigma, rng)
        ratios.append(metrics.vector_strength(j.times_in_channel(0), f) / vs0)
    observed = float(np.mean(ratios))
    predicted = np.exp(-2 * np.pi**2 * sigma**2 * f**2)
    assert abs(observed - predicted) < 0.10, (
        f"sigma={sigma * 1000:.1f} ms: observed {observed:.3f}, law predicts {predicted:.3f}")


# ===========================================================================
# E6 — Time-to-first-spike. Equations (27)-(29).
# ===========================================================================

def test_T6_1_budget_is_bounded_exactly():
    """At most one event per channel per frame, hence at most n_ch * n_frames
    events in total. This exactness is E6's distinctive practical virtue."""
    n_ch, duration, frame, hop = 8, 1.0, 0.025, 0.010
    enc = E.TTFS(n_channels=n_ch, e_min=0.0, frame=frame, hop=hop)
    drive = drive_for(E.TTFS, n_channels=n_ch, duration=duration)
    train = enc.encode_from_drive(drive, DT)
    n_frames = int(np.floor((duration - frame) / hop)) + 1
    assert len(train) <= n_ch * n_frames
    for m in range(n_frames):
        lo, hi = m * hop, m * hop + frame
        window = train.channel[(train.time >= lo) & (train.time < hi)]
        assert len(np.unique(window)) == len(window), f"channel fired twice in frame {m}"


def test_T6_2_latency_rank_inverts_energy_rank():
    """Within a frame, louder channels fire earlier — exactly, with Spearman
    correlation of -1 across the channels that fired."""
    n_ch, frame, hop = 8, 0.025, 0.010
    enc = E.TTFS(n_channels=n_ch, e_min=0.0, frame=frame, hop=hop)
    drive = drive_for(E.TTFS, n_channels=n_ch, duration=0.5)
    train = enc.encode_from_drive(drive, DT)
    checked = 0
    for m in range(1, 40):
        lo = m * hop
        sel = (train.time >= lo) & (train.time < lo + frame)
        if np.sum(sel) < 4:
            continue
        chans = train.channel[sel]
        lat = train.time[sel] - lo
        i0, i1 = int(round(lo / DT)), int(round((lo + frame) / DT))
        energy = np.sum(drive[chans, i0:i1] ** 2, axis=1)
        assert _spearman(energy, lat) == pytest.approx(-1.0, abs=1e-9), (
            f"frame {m}: rank correlation {_spearman(energy, lat):.4f}")
        checked += 1
    assert checked >= 5, "not enough populated frames to test"


def test_T6_3_lif_latency_matches_the_closed_form():
    """mode='lif': t = tau_m * ln(I / (I - theta)), equation (29)."""
    tau_m, theta = 0.02, 1.0
    enc = E.TTFS(n_channels=1, e_min=0.0, frame=0.025, hop=0.025,
                 tau_m=tau_m, theta=theta, mode="lif")
    drive = constant_drive(np.sqrt(4.0 / int(0.025 / DT)), n_channels=1, duration=0.025)
    train = enc.encode_from_drive(drive, DT)
    assert len(train) == 1
    I = np.sum(drive[0] ** 2)
    expected = tau_m * np.log(I / (I - theta))
    assert abs(train.time[0] - expected) < 1.5 * DT, (
        f"latency {train.time[0]:.6f} s, closed form {expected:.6f} s")


# ===========================================================================
# Corruption operators (SPEC §7) — used by P2 and by T5.4
# ===========================================================================

def test_corrupt_jitter_preserves_count_and_ordering():
    enc = E.LIF(n_channels=4, theta=1.0, tau_m=0.02)
    train = enc.encode_from_drive(drive_for(E.LIF), DT)
    out = corrupt.jitter(train, 0.002, np.random.default_rng(0))
    assert len(out) == len(train)
    assert np.all(np.diff(out.time) >= 0), "jitter must restore canonical order"
    assert np.all(out.time >= 0.0) and np.all(out.time <= train.duration)


def test_corrupt_channel_shift_drops_rather_than_wraps():
    enc = E.LIF(n_channels=4, theta=1.0, tau_m=0.02)
    train = enc.encode_from_drive(drive_for(E.LIF), DT)
    out = corrupt.channel_shift(train, 2)
    assert np.all(out.channel >= 2) and np.all(out.channel < 4)
    assert len(out) == int(np.sum(train.channel < 2))


def test_corrupt_delete_retains_expected_fraction():
    enc = E.LIF(n_channels=4, theta=1.0, tau_m=0.02)
    train = enc.encode_from_drive(drive_for(E.LIF, duration=4.0), DT)
    assert len(train) > 500, "need a well-populated train for a rate assertion"
    out = corrupt.delete(train, 0.3, np.random.default_rng(0))
    assert 0.65 < len(out) / len(train) < 0.75


def test_corrupt_randomise_times_preserves_channel_counts():
    enc = E.LIF(n_channels=4, theta=1.0, tau_m=0.02)
    train = enc.encode_from_drive(drive_for(E.LIF), DT)
    out = corrupt.randomise_times(train, np.random.default_rng(0))
    np.testing.assert_array_equal(train.counts_per_channel(),
                                  out.counts_per_channel())


# ===========================================================================
# Metrics (SPEC §6)
# ===========================================================================

def test_vector_strength_extremes():
    """1.0 for perfectly locked events, ~0 for uniformly distributed phase."""
    f = 100.0
    locked = np.arange(50) / f                      # exactly one per cycle
    assert metrics.vector_strength(locked, f) == pytest.approx(1.0, abs=1e-9)
    rng = np.random.default_rng(0)
    uniform = np.sort(rng.uniform(0, 1.0, 5000))
    assert metrics.vector_strength(uniform, f) < 0.1
    assert metrics.vector_strength(np.array([0.01]), f) == 0.0


def test_decoded_information_bounds():
    """Equation (38). Perfect classification of C equiprobable classes gives
    log2(C) bits; chance-level prediction gives zero."""
    perfect = np.eye(4) * 25
    assert metrics.decoded_information(perfect) == pytest.approx(2.0, abs=1e-9)
    chance = np.full((4, 4), 25.0 / 4)
    assert metrics.decoded_information(chance) == pytest.approx(0.0, abs=1e-9)


def test_event_rate_definitions():
    """Equations (34)-(35)."""
    train = SpikeTrain(
        channel=np.array([0, 1, 2, 3], dtype=np.int32),
        time=np.array([0.1, 0.2, 0.3, 0.4]),
        polarity=np.ones(4, dtype=np.int8),
        n_channels=4, duration=2.0, params={},
    )
    assert metrics.event_rate(train) == pytest.approx(2.0)
    assert metrics.rate_per_channel(train) == pytest.approx(0.5)
